djangoapp/blog/urls.py
from django.urls import path # type: ignore
from blog.views import index, page, post, created_by, category, tag, search

app_name = 'blog'

urlpatterns = [
    path('',  index, name='index'),
    path('page/<slug:slug>/',  page, name='page'),
    path('post/<slug:slug>/',  post, name='post'),
    path('created_by/<int:author_id>/',  created_by, name='created_by'),
    path('category/<slug:slug>/',  category, name='category'),
    path('tag/<slug:slug>/',  tag, name='tag'),
    path('search/',  search, name='search'),

]

djangoapp/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT)

djangoapp/blog/models.py
from django.db import models # type: ignore
from utils.rands import slogify_new
from django.contrib.auth.models import User
from utils.images import resize_image
from django.urls import reverse
from django_summernote.models import AbstractAttachment






class PostAttachment(AbstractAttachment):
    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self.file.name
        
        current_file_name = str(self.file.name) # Nome do cover atual
        super_save = super().save(*args, **kwargs)

        file_changed = False

        if self.file: # Verifica se o cover foi alterado
            file_changed = current_file_name != str(self.file.name) # Verifica se o cover é diferente
        
        if file_changed: # Verifica se o cover esta sendo alterado
            resize_image(self.file,900, True, 70)  # Redimensiona o cover

        #resize_image(self.cover, new_width=32, optimize=True, quality=60)

        return super_save


# criar tags de posts
class Tag(models.Model):
    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    name = models.CharField(max_length=200)
    slug = models.SlugField(
        unique=True, default=None, 
        blank=True, null=True,
        max_length=200
    )
    
    def save(self, *args, **kwargs): # Salva o slug
        if not self.slug:
            self.slug = slogify_new(self.name, 4)

        return super().save(*args, **kwargs)
    
    def __str__(self):
        return self.name

# criar categorias de posts    
class Category(models.Model): 
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=200)
    slug = models.SlugField(
        unique=True, default=None, 
        blank=True, null=True,
        max_length=200
    )

    def save(self, *args, **kwargs): # Salva o slug
        if not self.slug:
            self.slug = slogify_new(self.name, 4)

        return super().save(*args, **kwargs)
    
    def __str__(self):
        return self.name

class PostManager(models.Manager):  # Usar pots manager para evitar repetição do codigo
    def get_published(self):
        return self\
            .filter(is_published=True)\
            .order_by('-id')

# criar paginas de posts 
class Page(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(
        unique=True, default="", 
        blank=True, null=False,
        max_length=200
    )

    objectos = PostManager()

    content = models.TextField()
    is_published = models.BooleanField(
        default=False,
        help_text="Este campo precisa ser marcado para que o página seja publicada.",
    )

    def get_absolute_url(self): # retorna a url do post
        if not self.is_published:
            return reverse('blog:index')
        return reverse('blog:page', args=(self.slug,))

    def save(self, *args, **kwargs): # Salva o slug
        if not self.slug:
            self.slug = slogify_new(self.title, 4)

        return super().save(*args, **kwargs)
    def __str__(self):
        return self.title



    

class Post(models.Model):
    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    objectos = PostManager()

    title = models.CharField(max_length=200) # título do post
    slug = models.SlugField(       # slug do post que serve para identificar o post
        unique=True, default="", 
        blank=True, null=True,
        max_length=200
    )
    
    execerpt = models.CharField(max_length=130) # resumo do post mostrado na home

    
    is_published = models.BooleanField(     # verifica se o post foi publicado
        default=False,
        help_text="Este campo precisa ser marcado para que o post seja publicado.",
    )

    content = models.TextField()

    cover = models.ImageField(       # carregar uma imagem de capa (cover) para o post
        upload_to='assets/cover/%Y/%m/', 
        default='', 
        blank=True,    
    )

    cover_in_post_content = models.BooleanField(     # verifica se a imagem de capa deve ser mostrada no conteúdo do post
        default=True,
        help_text="Este campo precisa ser marcado para que a imagem de capa seja mostrada no conteúdo do post.",
    )

    created_at = models.DateTimeField(auto_now_add=True) # salvar a data de criação do post
    created_by = models.ForeignKey(     # salvar o usuário que criou o post
        User,
        on_delete=models.SET_NULL,
        blank=True, null=True,
        related_name='page_created_by',
    )
    updated_at = models.DateTimeField(auto_now=True) # salvar a data de atualização do post
    updated_by = models.ForeignKey(     # salvar o usuário que atualizou o post
        User,
        on_delete=models.SET_NULL,
        blank=True, null=True,
        related_name='page_updated_by',
    )

    tags = models.ManyToManyField(Tag, blank=True, default="") # cria uma relação de muitos para muitos, fazendo com que o post possa ter muitas tags

    category = models.ForeignKey(       # cria uma relação de um para muitos, faz com que muitos posts possam pertencer a uma mesma categoria
        Category,
        on_delete=models.SET_NULL,
        blank=True,                
        null=True,
        default=None,
    )
    
    def get_absolute_url(self): # retorna a url do post
        if not self.is_published:
            return reverse('blog:index')
        return reverse('blog:post', args=(self.slug,))

    def save(self, *args, **kwargs): # Salva o slug
        if not self.slug:       
            self.slug = slogify_new(self.title, 4)
        
        # configurar o tamanho da imagem de capa
        current_cover_name = str(self.cover.name) # Nome do cover atual
        super_save = super().save(*args, **kwargs)

        cover_changed = False

        if self.cover: # Verifica se o cover foi alterado
            cover_changed = current_cover_name != str(self.cover.name) # Verifica se o cover é diferente
        
        if cover_changed: # Verifica se o cover esta sendo alterado
            resize_image(self.cover,900, True, 70)  # Redimensiona o cover

        #resize_image(self.cover, new_width=32, optimize=True, quality=60)

        return super_save
    
    def __str__(self) -> str:
        return self.title

djangoapp/blog/views.py
from django.shortcuts import render # type: ignore
from django.core.paginator import Paginator # type: ignore
from blog.models import Post, Page
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import Http404 



POSTS_PER_PAGE = 9

# Create your views here.
def index(request):

    posts = Post.objectos.get_published()
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    if len(page_obj) == 0:
        raise Http404
    
    page_title = page_obj[0].category.name + ' - Categoria - '

    return render(
        request, 
        'blog/pages/index.html',

        {
            'page_obj': page_obj,
            'Page_title': 'Home '
        }
        
    )

def page(request, slug):

    page = (
        Page.objectos
             .filter(slug=slug)
             .filter(is_published=True)
             .first()
     )
    return render(
        request, 
        'blog/pages/page.html',

        {
            'page': page,
            'Page_title': 'Home '
        }
        
    )

def post(request, slug):
    post = (Post.objectos.get_published()
             .filter(slug=slug)
             .first()
     )

    return render(
        request, 
        'blog/pages/post.html',

        {
            'post': post,
            'Page_title': 'Home '
        }    
    )


def created_by(request, author_id):
    
    posts = Post.objectos.get_published()\
        .filter(created_by__pk=author_id)

    user = User.objects.filter(pk=author_id).first()

    if not user:
        raise Http404()
    
    user_full_name = user.username   
    if (user.first_name):  
        user_full_name = f'{user.first_name} {user.last_name}'

    page_title = f'Posts de {user_full_name} - '
    
    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(
        request, 
        'blog/pages/index.html',

        {
            'page_obj': page_obj,
            'Page_title': page_title
        }
        
    )


def category(request, slug):

    posts = Post.objectos.get_published()\
        .filter(category__slug=slug)
    

    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    if len(page_obj) == 0:
        raise Http404
    
    page_title = page_obj[0].category.name + ' - Categoria - '


    return render(
        request, 
        'blog/pages/index.html',

        {
            'page_obj': page_obj,
            'Page_title': page_title,
        }
        
    )




def tag(request, slug):

    posts = Post.objectos.get_published()\
        .filter(tags__slug=slug)
        

    paginator = Paginator(posts, POSTS_PER_PAGE)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    if len(page_obj) == 0:
        raise Http404
    
    page_title = page_obj[0].tags.first().name + ' - tag - '

    return render(
        request, 
        'blog/pages/index.html',

        {
            'page_obj': page_obj,
            'Page_title': page_title,
        }
        
    )

def search(request):

    search_value = request.GET.get('search', '').strip() 

    posts = (
        Post.objectos.get_published()\
        .filter(
            # titulo ou execerpt ou content contem o search_value
            Q(title__icontains=search_value) |
            Q(execerpt__icontains=search_value) |
            Q(content__icontains=search_value)

        )[:POSTS_PER_PAGE]
        
    )  



    return render(
        request, 
        'blog/pages/index.html',

        {
            'page_obj': posts,
            'search_value': search_value,
            'page_title': 'Home'
        }   
    )

djangoapp/blog/templates/blog/pages/index.html
<!-- Aqui vai carregar tudo onde tiver varios postes
  (buscas,usuarios, categorias, home,tags, etc.. ), 
  toda a parte que carrega uma lista de postes -->

{% extends "blog/base.html" %}

{% block content %}
  <main class="main-content section-wrapper">
    <div class="section-content-wide">
      <div class="section-gap">
        {% if page_obj %}
          <div class="card-grid">
            {% for post in page_obj %}
              {% include 'blog/partials/_post-card.html' with i=forloop.counter0 %}
            {% endfor %}
          </div>
        {% else %}
          <div class="not-found center">
            <h1> Nada encontrado🥺</h1>
            <p>Não conseguimos encontrar o que você estava procurando neste link, vamos voltar para a <a href="{% url 'blog:index' %}">home</a></p>
          </div>
        {% endif %}
      </div>
    </div>
  </main>
{% endblock content %}

djangoapp/blog/templates/blog/pages/page.html
<!-- Aqui é para carregar as paginas -->
{% extends "blog/base.html" %}

{% block content %}
    <main class="main-content section-wrapper">
        <div class="section-content-narrow">
            <div class="section-gap">
                <h1 class="center">{{page.title}}</h1>
                 {{page.content | safe}} 
            </div>
        </div>
    </main>
{% endblock content %}

djangoapp/blog/templates/blog/pages/post.html
<!-- Aqui é para carregar os postes-->

{% extends "blog/base.html" %}

{% block additional_head %}
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/codemirror.min.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/theme/dracula.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/codemirror.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/python/python.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/javascript/javascript.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/htmlmixed/htmlmixed.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/css/css.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/codemirror/5.62.2/mode/xml/xml.min.js"></script>
{% endblock additional_head %}

{% block content %}
<main class="main-content single-post section-wrapper">
  <div class="single-post-content section-content-narrow">
    <div class="single-post-gap section-gap">

      {% if post.cover and post.cover_in_post_content %} {% comment "" %} se tiver um cover (imagem) e estiver is_published {% endcomment %}
        <div class="single-post-cover pb-base center">
          <img 
          loading="lazy" 
          src="{{post.cover.url}}" 
          alt="{{post.title}}">
        </div>
      {% endif %}

      <h2 class="single-post-title pb-base center">
        {{post.title}}
      </h2>

      <div class="post-meta pb-base">
        <div class="post-meta-item">
            <a 
            class="post-meta-link" 
            href=" {% url "blog:created_by" post.created_by.pk %}">
            <i class="fa-solid fa-user"></i>

            <span>
              {# Verificar o autor #}

              {% if post.created_by.first_name %} {# Se tem um nome #}
                {{ post.created_by.first_name }}
                {{ post.created_by.last_name }}
              {% endif %}
            </span>

          </a>
        </div>
        <div class="post-meta-item">
          <span class="post-meta-link">
            <i class="fa-solid fa-calendar-days"></i>
            <span>
              {{post.created_at | date:'d/m/Y \à\s H:i'}}
            </span>
          </span>
        </div>
        {% if post.category %} {# verifica Se o tem uma categoria #}
          <div class="post-meta-item">
            <a 
              class="post-meta-link" 
              href="{% url "blog:category" post.category.slug %}">
              <i class="fa-solid fa-tag"></i>
              <span>
                {{post.category.name}}
              </span>
            </a>
          </div>
        {% endif %}
      </div>

      <p class="single-post-excerpt pb-base">
        {{ post.execerpt | safe }}
      </p>

      <div class="separator"></div>

      <div class="single-post-content">
        
        {{ post.content | safe }} 
      
        {% if post.tags.exists %} <!-- Verificar se existe tags-->
            <div class="post-tags">
              <span>Tags: </span>

              {% for tag in post.tags.all %}
                <a class="post-tag-link" href="{% url "blog:tag" tag.slug %}">
                  <i class="fa-solid fa-link"></i>
                  <span>{{tag.name}}</span>
                </a>
              {% endfor %}
            </div>       
        {% endif %}
      </div>
    
    </div>
  </div>
</main>

{% endblock content %}